version: '3.1'

services:
  database:
    image: 'postgres:13.3-alpine'
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - ./db/data/:/var/lib/postgresql/data/
      - ./db/sql/:/docker-entrypoint-initdb.d/
  rest_api:
    build: .
    ports:
      - 8080:8080
    env_file:
      - rest_api.env
