name: CI/CD
on:
  push:
    branches: [ master ]
    tags: '*'
  pull_request:


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.1.0
      - name: install
        run: poetry install
      - name: flake8
        run: poetry run flake8 tests/ louis/
      - name: mypy
        run: poetry run mypy tests/ louis/
      - name: black
        run: poetry run black tests/ louis/ --check
      - name: test
        run: poetry run pytest tests/ -vv
